<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ApplicationIcon>ACATWatch.ico</ApplicationIcon>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyTitle>ACATWatch</AssemblyTitle>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(SolutionRoot)ACATResources\ACATResources.csproj" />
    <ProjectReference Include="$(SolutionRoot)Libraries\ACATCore\ACAT.Core.csproj" />
    <ProjectReference Include="$(SolutionRoot)Libraries\ACATExtension\ACAT.Extension.csproj" />
    <ProjectReference Include="..\AppCommon\AppCommon.csproj" />
  </ItemGroup>
</Project>