<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyTitle>ACAT Dashboard</AssemblyTitle>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)ACATResources\ACATResources.csproj" />
    <ProjectReference Include="$(SolutionDir)Libraries\ACATCore\ACAT.Core.csproj" />
    <ProjectReference Include="$(SolutionDir)Libraries\ACATExtension\ACAT.Extension.csproj" />
    <ProjectReference Include="..\AppCommon\AppCommon.csproj" />
  </ItemGroup>
</Project>