//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACAT.Extensions.Default.WordPredictors.PresageWCF
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACAT.Extensions.Default.WordPredictors.Presage.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database.db.
        /// </summary>
        internal static string database_db {
            get {
                return ResourceManager.GetString("database_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (http://presage.sourceforge.net/).
        /// </summary>
        internal static string http_presage_sourceforge_net {
            get {
                return ResourceManager.GetString("http_presage_sourceforge_net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intelligent predictive text engine created by Matteo Vescovi. .
        /// </summary>
        internal static string intelligent_predictive_text_engine_created_by_Matteo_Vescovi {
            get {
                return ResourceManager.GetString("intelligent_predictive_text_engine_created_by_Matteo_Vescovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learn.db.
        /// </summary>
        internal static string learn_db {
            get {
                return ResourceManager.GetString("learn_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictive text functionality is powered by Presage, the .
        /// </summary>
        internal static string Predictive_text_functionality_is_powered_by_Presage_the {
            get {
                return ResourceManager.GetString("Predictive_text_functionality_is_powered_by_Presage_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESAGE.
        /// </summary>
        internal static string PRESAGE {
            get {
                return ResourceManager.GetString("PRESAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to presage.xml.
        /// </summary>
        internal static string presage_xml {
            get {
                return ResourceManager.GetString("presage_xml", resourceCulture);
            }
        }
    }
}
