//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACAT.Extensions.Hawking.FunctionalAgents.NewFile
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewFileAgent.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear File Name?.
        /// </summary>
        internal static string Clear_File_Name {
            get {
                return ResourceManager.GetString("Clear_File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create folder .
        /// </summary>
        internal static string Could_not_create_folder {
            get {
                return ResourceManager.GetString("Could_not_create_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create file .
        /// </summary>
        internal static string Create_file {
            get {
                return ResourceManager.GetString("Create_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string Create_New {
            get {
                return ResourceManager.GetString("Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter File Name:.
        /// </summary>
        internal static string Enter_File_Name {
            get {
                return ResourceManager.GetString("Enter_File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Lecture Manager?.
        /// </summary>
        internal static string Exit_Lecture_Manager {
            get {
                return ResourceManager.GetString("Exit_Lecture_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit without creating?.
        /// </summary>
        internal static string Exit_without_creating {
            get {
                return ResourceManager.GetString("Exit_without_creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.
        /// </summary>
        internal static string File_already_exists {
            get {
                return ResourceManager.GetString("File_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture Mgr.
        /// </summary>
        internal static string Lecture_Mgr {
            get {
                return ResourceManager.GetString("Lecture_Mgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of File:.
        /// </summary>
        internal static string Name_of_File {
            get {
                return ResourceManager.GetString("Name_of_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All?.
        /// </summary>
        internal static string Set_All {
            get {
                return ResourceManager.GetString("Set_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Paragraph Mode?.
        /// </summary>
        internal static string Set_Paragraph_Mode {
            get {
                return ResourceManager.GetString("Set_Paragraph_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Sentence Mode?.
        /// </summary>
        internal static string Set_Sentence_Mode {
            get {
                return ResourceManager.GetString("Set_Sentence_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak now?.
        /// </summary>
        internal static string Speak_now {
            get {
                return ResourceManager.GetString("Speak_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking. Leave?.
        /// </summary>
        internal static string Speaking_Leave {
            get {
                return ResourceManager.GetString("Speaking_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
    }
}
