<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>
    <ItemGroup>
    <Reference Include="System" />
  </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Update="StringResources.en.resx">
        <Generator>PublicRexXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="StringResources.es.resx">
        <Generator>PublicRexXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="StringResources.resx">
        <Generator>PublicRexXFileCodeGenerator</Generator>
      </EmbeddedResource>
    </ItemGroup>
  <PropertyGroup>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>
  
  <!-- Copy Assets Directories -->
  <ItemGroup>
    <Assets Include="$(SolutionDir)Assets\**\*">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Assets>
  </ItemGroup>
  
  <Target Name="CopyAssetFiles" AfterTargets="Build">
    <Message Text="Copy Asssets Files" Importance="high" />
    <MakeDir Directories="$(OutputPath)Assets\%(Assets.RecursiveDir)" />
    <Copy 
      SourceFiles="@(Assets)" 
      DestinationFiles="$(OutputPath)Assets\%(Assets.RecursiveDir)%(Filename)%(Extension)" 
      SkipUnchangedFiles="true" />
  </Target>
  
  <!-- Copy Default User Install Files -->
  <ItemGroup>
    <DefaultUserFiles Include="$(SolutionDir)\Applications\Install\Users\**\*">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </DefaultUserFiles>
  </ItemGroup>
  
  <Target Name="CopyInstallFiles" AfterTargets="Build">
    <Message Text="Copy Install Files" Importance="high" />
    <Copy 
      SourceFiles="@(DefaultUserFiles)" 
      DestinationFiles="$(OutputPath)Install\Users\%(DefaultUserFiles.RecursiveDir)%(Filename)%(Extension)" 
      SkipUnchangedFiles="true" />
  </Target>
  
  <!-- Copy PanelConfigs -->
  <ItemGroup>
    <PanelConfigs Include="$(ProjectDir)\panelconfigs\**\*">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </PanelConfigs>
  </ItemGroup>
  
  <Target Name="CopyPanelConfigs" AfterTargets="Build">
    <Message Text="Copy Panel Config Files" Importance="high" />
    <Copy 
      SourceFiles="@(PanelConfigs)" 
      DestinationFiles="$(OutputPath)\panelconfigs\%(PanelConfigs.RecursiveDir)%(Filename)%(Extension)" 
      SkipUnchangedFiles="true" />
    </Target>
  
  <!-- Copy ConvAssist Static Files -->
  <ItemGroup>
    <ConvAssistStatic Include="$(SolutionDir)\Applications\Install\en\**\*">
      <Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
    </ConvAssistStatic>
  </ItemGroup>
  <Target Name="CopyStaticConvAssist" AfterTargets="Build">
    <Message Text="Copy Static ConvAssist Files" Importance="high" />
    <!-- Copy files while preserving subfolders -->
    <Copy 
      SourceFiles="@(ConvAssistStatic)" 
      DestinationFiles="$(OutputPath)en\%(ConvAssistStatic.RecursiveDir)%(Filename)%(Extension)" 
      SkipUnchangedFiles="true" />
  </Target>
  <!-- Copy ConvAssist Application -->
  <Target Name="UnzipDependency" AfterTargets="Build">
    <!-- Define paths -->
    <PropertyGroup>
      <ZipFile>$(SolutionDir)\Applications\Install\ConvAssistApp\ConvAssist.zip</ZipFile>
      <ExtractedDir>$(BaseOutputPath)\UnzippedDependency\</ExtractedDir>
      <UnzipFlagFile>$(ExtractedDir).unzipped</UnzipFlagFile>
    </PropertyGroup>
    <!-- Only unzip if the flag file doesn't exist -->
    <Message Text="Unzipping dependency files from $(ZipFile) to $(ExtractedDir)" Condition="!Exists('$(UnzipFlagFile)')" Importance="high" />
    <Exec Condition="!Exists('$(UnzipFlagFile)')" Command="powershell -Command &quot;Expand-Archive -Path '$(ZipFile)' -DestinationPath '$(ExtractedDir)' -Force&quot;" />
    <Message Text="Unzipped dependency files to $(ExtractedDir)" Condition="!Exists('$(UnzipFlagFile)')" Importance="high" />
    <!-- Create a flag file to avoid re-extraction -->
    <WriteLinesToFile Condition="!Exists('$(UnzipFlagFile)')" File="$(UnzipFlagFile)" Lines="Unzipped on $(MSBuildThisFileFullPath)" Overwrite="true" />
    <Message Text="Copy ConvAssist App" Importance="high" />
    <!-- Copy contents to OutputPath -->
    <ItemGroup>
      <DependencyFiles Include="$(ExtractedDir)**\*" />
    </ItemGroup>
    <Message Text="Copying dependency files to output directory: $(OutDir)" Importance="high" />
    <Copy SourceFiles="@(DependencyFiles)" DestinationFolder="$(OutDir)\ConvAssistApp\%(RecursiveDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
