<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
    <ItemGroup>
    <Reference Include="System" />
  </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Update="StringResources.en.resx">
        <Generator>PublicRexXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="StringResources.es.resx">
        <Generator>PublicRexXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="StringResources.resx">
        <Generator>PublicRexXFileCodeGenerator</Generator>
      </EmbeddedResource>
    </ItemGroup>

  <ItemGroup>
    <!-- Use Link to preserve folder structure in metadata -->
    <Assets Include="$(ProjectDir)en\**\*">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Assets>
  </ItemGroup>

  <Target Name="CopyAssetFiles" AfterTargets="Build">
    <!-- Ensure destination directories exist -->
    <MakeDir Directories="$(OutputPath)Assets\%(Assets.RecursiveDir)" />

    <!-- Copy files while preserving subfolders -->
    <Copy
      SourceFiles="@(Assets)"
      DestinationFiles="$(OutputPath)en\%(Assets.RecursiveDir)%(Filename)%(Extension)"
      SkipUnchangedFiles="true" />
  </Target>
</Project>
