//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACAT.Extensions.Default.UI.Dialogs
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aster.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACAT - Assistive Context-Aware Toolkit.
        /// </summary>
        internal static string ACAT_Assistive_Context_Aware_Toolkit {
            get {
                return ResourceManager.GetString("ACAT_Assistive_Context_Aware_Toolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACAT Mute.
        /// </summary>
        internal static string ACAT_Mute {
            get {
                return ResourceManager.GetString("ACAT_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACAT Scanner Design.
        /// </summary>
        internal static string ACAT_Scanner_Design {
            get {
                return ResourceManager.GetString("ACAT_Scanner_Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACAT Talk Window.
        /// </summary>
        internal static string ACAT_Talk_Window {
            get {
                return ResourceManager.GetString("ACAT_Talk_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept time.
        /// </summary>
        internal static string Accept_time {
            get {
                return ResourceManager.GetString("Accept_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; already exists.
        /// </summary>
        internal static string already_exists {
            get {
                return ResourceManager.GetString("already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Pronunciation.
        /// </summary>
        internal static string Alternative_Pronunciation {
            get {
                return ResourceManager.GetString("Alternative_Pronunciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Pronunciations.
        /// </summary>
        internal static string Alternative_Pronunciations {
            get {
                return ResourceManager.GetString("Alternative_Pronunciations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_exit {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aster Abbreviations.
        /// </summary>
        internal static string Aster_Abbreviations {
            get {
                return ResourceManager.GetString("Aster_Abbreviations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aster Edit/Add Abbreviation.
        /// </summary>
        internal static string Aster_Edit_Add_Abbreviation {
            get {
                return ResourceManager.GetString("Aster_Edit_Add_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ate.
        /// </summary>
        internal static string ate {
            get {
                return ResourceManager.GetString("ate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-save scanner&apos;s last position.
        /// </summary>
        internal static string Auto_save_scanner_last_position {
            get {
                return ResourceManager.GetString("Auto_save_scanner_last_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        internal static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backspace.
        /// </summary>
        internal static string Backspace {
            get {
                return ResourceManager.GetString("Backspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bat.
        /// </summary>
        internal static string bat {
            get {
                return ResourceManager.GetString("bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beep on Select.
        /// </summary>
        internal static string Beep_on_Select {
            get {
                return ResourceManager.GetString("Beep_on_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beet.
        /// </summary>
        internal static string beet {
            get {
                return ResourceManager.GetString("beet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bet.
        /// </summary>
        internal static string bet {
            get {
                return ResourceManager.GetString("bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes not saved. Quit?.
        /// </summary>
        internal static string Changes_not_saved_Quit {
            get {
                return ResourceManager.GetString("Changes_not_saved_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes not saved.
        ///Quit anyway?.
        /// </summary>
        internal static string Changes_not_saved_Quit_anyway {
            get {
                return ResourceManager.GetString("Changes_not_saved_Quit_anyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2013-2015 Intel Corporation.
        /// </summary>
        internal static string Copyright_Intel_Corporation {
            get {
                return ResourceManager.GetString("Copyright_Intel_Corporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd, MMMM d, yyyy.
        /// </summary>
        internal static string dddd_MMMM_yyyy {
            get {
                return ResourceManager.GetString("dddd_MMMM_yyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        internal static string Defaults {
            get {
                return ResourceManager.GetString("Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        internal static string Delete1 {
            get {
                return ResourceManager.GetString("Delete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  digits.
        /// </summary>
        internal static string digits {
            get {
                return ResourceManager.GetString("digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digits: 0  to  .
        /// </summary>
        internal static string Digits_to {
            get {
                return ResourceManager.GetString("Digits_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doomsday.
        /// </summary>
        internal static string doomsday {
            get {
                return ResourceManager.GetString("doomsday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eat.
        /// </summary>
        internal static string eat {
            get {
                return ResourceManager.GetString("eat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit/Add Alternative Pronunciation.
        /// </summary>
        internal static string Edit_Add_Alternative_Pronunciation {
            get {
                return ResourceManager.GetString("Edit_Add_Alternative_Pronunciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable audit log.
        /// </summary>
        internal static string Enable_audit_log {
            get {
                return ResourceManager.GetString("Enable_audit_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Dynamic Learning.
        /// </summary>
        internal static string Enable_Dynamic_Learning {
            get {
                return ResourceManager.GetString("Enable_Dynamic_Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Column.
        /// </summary>
        internal static string Every_Column {
            get {
                return ResourceManager.GetString("Every_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Half.
        /// </summary>
        internal static string Every_Half {
            get {
                return ResourceManager.GetString("Every_Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Row.
        /// </summary>
        internal static string Every_Row {
            get {
                return ResourceManager.GetString("Every_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        internal static string Exit1 {
            get {
                return ResourceManager.GetString("Exit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand abbreviations on separator.
        /// </summary>
        internal static string Expand_abbreviations_on_separator {
            get {
                return ResourceManager.GetString("Expand_abbreviations_on_separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (50 to 200).
        /// </summary>
        internal static string FiftyToTwoHundred {
            get {
                return ResourceManager.GetString("FiftyToTwoHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (50 to 250).
        /// </summary>
        internal static string FiftyToTwoHundredAndFifty {
            get {
                return ResourceManager.GetString("FiftyToTwoHundredAndFifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Repeat Time.
        /// </summary>
        internal static string First_Repeat_Time {
            get {
                return ResourceManager.GetString("First_Repeat_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string General_Settings {
            get {
                return ResourceManager.GetString("General_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good..
        /// </summary>
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesitate time.
        /// </summary>
        internal static string Hesitate_time {
            get {
                return ResourceManager.GetString("Hesitate_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide scanners on idle.
        /// </summary>
        internal static string Hide_scanners_on_idle {
            get {
                return ResourceManager.GetString("Hide_scanners_on_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization error.
        /// </summary>
        internal static string Initialization_error {
            get {
                return ResourceManager.GetString("Initialization_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Rate setting.
        /// </summary>
        internal static string Invalid_Rate_setting {
            get {
                return ResourceManager.GetString("Invalid_Rate_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Volume setting.
        /// </summary>
        internal static string Invalid_Volume_setting {
            get {
                return ResourceManager.GetString("Invalid_Volume_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Width.
        /// </summary>
        internal static string Line_Width {
            get {
                return ResourceManager.GetString("Line_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Message&gt;.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h:mm:ss tt.
        /// </summary>
        internal static string mm_ss_tt {
            get {
                return ResourceManager.GetString("mm_ss_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Grid Settings.
        /// </summary>
        internal static string Mouse_Grid_Settings {
            get {
                return ResourceManager.GetString("Mouse_Grid_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Radar Settings.
        /// </summary>
        internal static string Mouse_Radar_Settings {
            get {
                return ResourceManager.GetString("Mouse_Radar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Speed.
        /// </summary>
        internal static string Mouse_Speed {
            get {
                return ResourceManager.GetString("Mouse_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Sweeps.
        /// </summary>
        internal static string Mouse_Sweeps {
            get {
                return ResourceManager.GetString("Mouse_Sweeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Settings.
        /// </summary>
        internal static string Mute_Settings {
            get {
                return ResourceManager.GetString("Mute_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1 to 15).
        /// </summary>
        internal static string OneToFifteen {
            get {
                return ResourceManager.GetString("OneToFifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Term.
        /// </summary>
        internal static string Original_Term {
            get {
                return ResourceManager.GetString("Original_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        internal static string PIN {
            get {
                return ResourceManager.GetString("PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN cannot be empty.
        /// </summary>
        internal static string PIN_cannot_be_empty {
            get {
                return ResourceManager.GetString("PIN_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN contains non-numeric characters.
        /// </summary>
        internal static string PIN_contains_non_numeric_characters {
            get {
                return ResourceManager.GetString("PIN_contains_non_numeric_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN has digits outside of the valid range.
        /// </summary>
        internal static string PIN_has_digits_outside_of_the_valid_range {
            get {
                return ResourceManager.GetString("PIN_has_digits_outside_of_the_valid_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN length has to be between .
        /// </summary>
        internal static string PIN_length_has_to_be_between {
            get {
                return ResourceManager.GetString("PIN_length_has_to_be_between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch.
        /// </summary>
        internal static string Pitch {
            get {
                return ResourceManager.GetString("Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a term!.
        /// </summary>
        internal static string Please_enter_term {
            get {
                return ResourceManager.GetString("Please_enter_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:12 PM.
        /// </summary>
        internal static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presage Software used for word prediction.
        /// </summary>
        internal static string Presage_Software_used_for_word_prediction {
            get {
                return ResourceManager.GetString("Presage_Software_used_for_word_prediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronunciation cannot be empty!.
        /// </summary>
        internal static string Pronunciation_cannot_be_empty {
            get {
                return ResourceManager.GetString("Pronunciation_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronunciation for &apos;.
        /// </summary>
        internal static string Pronunciation_for {
            get {
                return ResourceManager.GetString("Pronunciation_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement Term.
        /// </summary>
        internal static string Replacement_Term {
            get {
                return ResourceManager.GetString("Replacement_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default settings?.
        /// </summary>
        internal static string Restore_default_settings {
            get {
                return ResourceManager.GetString("Restore_default_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retain Talk window text on close.
        /// </summary>
        internal static string Retain_Talk_window_text_on_close {
            get {
                return ResourceManager.GetString("Retain_Talk_window_text_on_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotating Speed.
        /// </summary>
        internal static string Rotating_Speed {
            get {
                return ResourceManager.GetString("Rotating_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotating Sweeps.
        /// </summary>
        internal static string Rotating_Sweeps {
            get {
                return ResourceManager.GetString("Rotating_Sweeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Save changes?.
        /// </summary>
        internal static string Save_changes {
            get {
                return ResourceManager.GetString("Save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings?.
        /// </summary>
        internal static string Save_settings {
            get {
                return ResourceManager.GetString("Save_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Iterations.
        /// </summary>
        internal static string Scan_Iterations {
            get {
                return ResourceManager.GetString("Scan_Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Settings.
        /// </summary>
        internal static string Scan_Settings {
            get {
                return ResourceManager.GetString("Scan_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Times.
        /// </summary>
        internal static string Scan_Times {
            get {
                return ResourceManager.GetString("Scan_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Locked.
        /// </summary>
        internal static string Screen_Locked {
            get {
                return ResourceManager.GetString("Screen_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Desktop.
        /// </summary>
        internal static string Show_Desktop {
            get {
                return ResourceManager.GetString("Show_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show glass under Talk window.
        /// </summary>
        internal static string Show_glass_under_Talk_window {
            get {
                return ResourceManager.GetString("Show_glass_under_Talk_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Talk window on startup.
        /// </summary>
        internal static string Show_Talk_window_on_startup {
            get {
                return ResourceManager.GetString("Show_Talk_window_on_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start from last cursor position.
        /// </summary>
        internal static string Start_from_last_cursor_position {
            get {
                return ResourceManager.GetString("Start_from_last_cursor_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepping time.
        /// </summary>
        internal static string Stepping_time {
            get {
                return ResourceManager.GetString("Stepping_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Application.
        /// </summary>
        internal static string Switch_Application {
            get {
                return ResourceManager.GetString("Switch_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Apps.
        /// </summary>
        internal static string Switch_Apps {
            get {
                return ResourceManager.GetString("Switch_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        internal static string t {
            get {
                return ResourceManager.GetString("t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab.
        /// </summary>
        internal static string tab {
            get {
                return ResourceManager.GetString("tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Scan time.
        /// </summary>
        internal static string Tab_Scan_time {
            get {
                return ResourceManager.GetString("Tab_Scan_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk.
        /// </summary>
        internal static string Talk {
            get {
                return ResourceManager.GetString("Talk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tea.
        /// </summary>
        internal static string tea {
            get {
                return ResourceManager.GetString("tea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test1 {
            get {
                return ResourceManager.GetString("Test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to .
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type this: .
        /// </summary>
        internal static string Type_this {
            get {
                return ResourceManager.GetString("Type_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Change?.
        /// </summary>
        internal static string Undo_Change {
            get {
                return ResourceManager.GetString("Undo_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Corpus Models for Word Prediction.
        /// </summary>
        internal static string Use_Corpus_Models_for_Word_Prediction {
            get {
                return ResourceManager.GetString("Use_Corpus_Models_for_Word_Prediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.00.00.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Speed.
        /// </summary>
        internal static string Vertical_Speed {
            get {
                return ResourceManager.GetString("Vertical_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Sweeps.
        /// </summary>
        internal static string Vertical_Sweeps {
            get {
                return ResourceManager.GetString("Vertical_Sweeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Settings.
        /// </summary>
        internal static string Voice_Settings {
            get {
                return ResourceManager.GetString("Voice_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Count.
        /// </summary>
        internal static string Word_Count {
            get {
                return ResourceManager.GetString("Word_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word List Hesitate time.
        /// </summary>
        internal static string Word_List_Hesitate_time {
            get {
                return ResourceManager.GetString("Word_List_Hesitate_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Prediction.
        /// </summary>
        internal static string Word_Prediction {
            get {
                return ResourceManager.GetString("Word_Prediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Prediction Settings.
        /// </summary>
        internal static string Word_Prediction_Settings {
            get {
                return ResourceManager.GetString("Word_Prediction_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made changes.
        ///Save?.
        /// </summary>
        internal static string You_have_made_changes_Save {
            get {
                return ResourceManager.GetString("You_have_made_changes_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new PIN is .
        /// </summary>
        internal static string Your_new_PIN_is {
            get {
                return ResourceManager.GetString("Your_new_PIN_is", resourceCulture);
            }
        }
    }
}
