//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCIInterfaceUtilities.ResourcesUtils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BCIInterfaceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BCIInterfaceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCIInterfaceUtilities.ResourcesUtils.BCIInterfaceResource", typeof(BCIInterfaceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate now.
        /// </summary>
        internal static string CalibrateNow {
            get {
                return ResourceManager.GetString("CalibrateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate Opt..
        /// </summary>
        internal static string CalibrateOptional {
            get {
                return ResourceManager.GetString("CalibrateOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration in progress. Please focus on the highlighted green target area.
        /// </summary>
        internal static string CalibrationInProgrressPrompt {
            get {
                return ResourceManager.GetString("CalibrationInProgrressPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Mode Calibration: 
        ///Enables selection of large sized regions on the Main Talk UI. With default values, this calibration takes ~ 2 mins..
        /// </summary>
        internal static string HintBoxCalibrationScreen {
            get {
                return ResourceManager.GetString("HintBoxCalibrationScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing Opt enabled.
        /// </summary>
        internal static string HintCalibrationBeginACATEnalbed {
            get {
                return ResourceManager.GetString("HintCalibrationBeginACATEnalbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must complete calibrations before proceeding.
        /// </summary>
        internal static string HintCalibrationBeginACATNotEnalbed {
            get {
                return ResourceManager.GetString("HintCalibrationBeginACATNotEnalbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect EEG data for future eyes open close detection.
        /// </summary>
        internal static string HintEyesOpenCloseCalibration {
            get {
                return ResourceManager.GetString("HintEyesOpenCloseCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of iterations per target.
        /// </summary>
        internal static string HintIterationstarget {
            get {
                return ResourceManager.GetString("HintIterationstarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Mode Calibration:​
        ///enables selection of small sized regions on the Main Talk UI. With default values, this calibration takes ~ 3 mins..
        /// </summary>
        internal static string HintKeyboardLeftCalibrationScreen {
            get {
                return ResourceManager.GetString("HintKeyboardLeftCalibrationScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Keyboard Mode Calibration: ​
        ///enables selection of small sized regions on the Main Talk UI. With default values, this calibration takes ~ 4 mins..
        /// </summary>
        internal static string HintKeyboardRightCalibrationScreen {
            get {
                return ResourceManager.GetString("HintKeyboardRightCalibrationScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum score needed for successful calibration.
        /// </summary>
        internal static string HintMinimumScore {
            get {
                return ResourceManager.GetString("HintMinimumScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of targets to be shown during calibration.
        /// </summary>
        internal static string HintNumberTargets {
            get {
                return ResourceManager.GetString("HintNumberTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the mapping of the calibration mode to the specific UI region.
        /// </summary>
        internal static string HintReMapCalibrations {
            get {
                return ResourceManager.GetString("HintReMapCalibrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning speed controls how fast the regions are highlighted on the screen.
        /// </summary>
        internal static string HintScanningTime {
            get {
                return ResourceManager.GetString("HintScanningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence Mode Calibration:​
        ///enables selection of medium sized regions on the Main Talk UI. With default values, this calibration takes ~ 2 mins..
        /// </summary>
        internal static string HintSentenceCalibrationScreen {
            get {
                return ResourceManager.GetString("HintSentenceCalibrationScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-run Signal Check to verify the signal quality.
        /// </summary>
        internal static string HintSignalCheck {
            get {
                return ResourceManager.GetString("HintSignalCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-run trigger test to check whether the Trigger sensor is working correctly.
        /// </summary>
        internal static string HintTriggerCheck {
            get {
                return ResourceManager.GetString("HintTriggerCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Word Mode Calibration: ​
        ///enables selection of medium sized regions on the Main Talk UI. With default values, this calibration takes ~ 4 mins..
        /// </summary>
        internal static string HintWordCalibrationScreen {
            get {
                return ResourceManager.GetString("HintWordCalibrationScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target # .
        /// </summary>
        internal static string IterationNumber {
            get {
                return ResourceManager.GetString("IterationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalibrate.
        /// </summary>
        internal static string Recalibrate {
            get {
                return ResourceManager.GetString("Recalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning time:.
        /// </summary>
        internal static string ScanningTime {
            get {
                return ResourceManager.GetString("ScanningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Typing.
        /// </summary>
        internal static string StartTyping {
            get {
                return ResourceManager.GetString("StartTyping", resourceCulture);
            }
        }
    }
}
