<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\Directory.Build.props" />

  <PropertyGroup>
    <!-- Compute ExtensionPath as path relative to the solution directory -->
    <!-- <ExtensionPath>\Extensions\</ExtensionPath> -->
    <ExtensionPath>$([System.String]::Copy('$(MSBuildProjectDirectory)').Replace('$(SolutionDir)', ''))</ExtensionPath>

    <!-- Final paths for this project -->
    <OutputPath>$(BuildPath)$(ExtensionPath)\</OutputPath>
    <IntermediateOutputPath>$(IntermediatePath)$(ExtensionPath)\</IntermediateOutputPath>
  </PropertyGroup>
</Project>
