<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\Directory.Build.props" />
  <PropertyGroup>
    <ExtensionPath>$([System.String]::Copy($(MSBuildProjectDirectory)).Replace($(SolutionDir), ""))</ExtensionPath>
    <IntermediateOutputPath>$(BaseOutputPath)\obj\$(Platform)\$(Configuration)\$(ExtensionPath)\</IntermediateOutputPath>
    <OutputPath>$(BuildPath)\$(ExtensionPath)\</OutputPath>
</PropertyGroup>
</Project>