//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACAT.Extensions.Hawking.FunctionalAgents.LectureManager
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LectureManagerAgent.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory .
        /// </summary>
        internal static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  does not exist.
        /// </summary>
        internal static string does_not_exist {
            get {
                return ResourceManager.GetString("does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dr.
        /// </summary>
        internal static string dr {
            get {
                return ResourceManager.GetString("dr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to etc.
        /// </summary>
        internal static string etc {
            get {
                return ResourceManager.GetString("etc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------EXIT-------------------.
        /// </summary>
        internal static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Lecture Manager?.
        /// </summary>
        internal static string Exit_Lecture_Manager {
            get {
                return ResourceManager.GetString("Exit_Lecture_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture Mgr.
        /// </summary>
        internal static string Lecture_Mgr {
            get {
                return ResourceManager.GetString("Lecture_Mgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mr.
        /// </summary>
        internal static string mr {
            get {
                return ResourceManager.GetString("mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mrs.
        /// </summary>
        internal static string mrs {
            get {
                return ResourceManager.GetString("mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string Open_File {
            get {
                return ResourceManager.GetString("Open_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        internal static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUSED.
        /// </summary>
        internal static string PAUSED {
            get {
                return ResourceManager.GetString("PAUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prof.
        /// </summary>
        internal static string prof {
            get {
                return ResourceManager.GetString("prof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All?.
        /// </summary>
        internal static string Set_All {
            get {
                return ResourceManager.GetString("Set_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Paragraph Mode?.
        /// </summary>
        internal static string Set_Paragraph_Mode {
            get {
                return ResourceManager.GetString("Set_Paragraph_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Sentence Mode?.
        /// </summary>
        internal static string Set_Sentence_Mode {
            get {
                return ResourceManager.GetString("Set_Sentence_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak now?.
        /// </summary>
        internal static string Speak_now {
            get {
                return ResourceManager.GetString("Speak_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking....
        /// </summary>
        internal static string Speaking {
            get {
                return ResourceManager.GetString("Speaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEAKING ALL.
        /// </summary>
        internal static string SPEAKING_ALL {
            get {
                return ResourceManager.GetString("SPEAKING_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking. Leave?.
        /// </summary>
        internal static string Speaking_Leave {
            get {
                return ResourceManager.GetString("Speaking_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEAKING PARAGRAPH.
        /// </summary>
        internal static string SPEAKING_PARAGRAPH {
            get {
                return ResourceManager.GetString("SPEAKING_PARAGRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEAKING SENTENCE.
        /// </summary>
        internal static string SPEAKING_SENTENCE {
            get {
                return ResourceManager.GetString("SPEAKING_SENTENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEAKING.
        /// </summary>
        internal static string SPEAKING1 {
            get {
                return ResourceManager.GetString("SPEAKING1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st.
        /// </summary>
        internal static string st {
            get {
                return ResourceManager.GetString("st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
    }
}
