<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>AnimationPOCDemo</AssemblyName>
    <RootNamespace>ACAT.Experimental.AnimationPOC.Demo</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x64</Platforms>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>obj\$(Configuration)\</IntermediateOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnimationPOC\AnimationPOC.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>
</Project>
