//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACAT.Extensions.Hawking.FunctionalAgents.FileBrowser
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileBrowserAgent.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit File Browser?.
        /// </summary>
        internal static string Exit_File_Browser {
            get {
                return ResourceManager.GetString("Exit_File_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Browser.
        /// </summary>
        internal static string File_Browser {
            get {
                return ResourceManager.GetString("File_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .	------------- NEXT PAGE  -------------.
        /// </summary>
        internal static string NEXT_PAGE {
            get {
                return ResourceManager.GetString("NEXT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------- NO FILES FOUND -------------.
        /// </summary>
        internal static string NO_FILES_FOUND {
            get {
                return ResourceManager.GetString("NO_FILES_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No program associated with file. Open anyway?.
        /// </summary>
        internal static string No_program_associated_with_file_Open_anyway {
            get {
                return ResourceManager.GetString("No_program_associated_with_file_Open_anyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Notepad.
        /// </summary>
        internal static string Notepad {
            get {
                return ResourceManager.GetString("Notepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open .
        /// </summary>
        internal static string Open1 {
            get {
                return ResourceManager.GetString("Open1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page .
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .	------------- PREVIOUS PAGE  -------------.
        /// </summary>
        internal static string PREVIOUS_PAGE {
            get {
                return ResourceManager.GetString("PREVIOUS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .	------------- SORT BY DATE -------------.
        /// </summary>
        internal static string SORT_BY_DATE {
            get {
                return ResourceManager.GetString("SORT_BY_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .	------------- SORT BY NAME -------------.
        /// </summary>
        internal static string SORT_BY_NAME {
            get {
                return ResourceManager.GetString("SORT_BY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string SuspensionPoints {
            get {
                return ResourceManager.GetString("SuspensionPoints", resourceCulture);
            }
        }
    }
}
