<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <ApplicationIcon>..\..\Assets\Images\ACATTalk.ico</ApplicationIcon>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyTitle>ACAT Dashboard</AssemblyTitle>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ACATResources\ACATResources.csproj" />
    <ProjectReference Include="$(SolutionDir)Libraries\ACATCore\ACAT.Core.csproj" />
    <ProjectReference Include="$(SolutionDir)Libraries\ACATExtension\ACAT.Extension.csproj" />
    <ProjectReference Include="$(SolutionDir)Extensions\ACAT.Extensions.Onboarding\ACAT.Extensions.Onboarding.csproj" />
    <ProjectReference Include="..\..\Extensions\ACAT.Extensions.UI\ACAT.Extensions.UI.csproj" />
    <ProjectReference Include="..\AppCommon\AppCommon.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Xaml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Data" />
    <Reference Include="System.Deployment" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>