//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACAT.Extensions.Hawking.FunctionalAgents.Abbreviations
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbbreviationsAgent.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation.
        /// </summary>
        internal static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviations.
        /// </summary>
        internal static string Abbreviations {
            get {
                return ResourceManager.GetString("Abbreviations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviations Editor.
        /// </summary>
        internal static string Abbreviations_Editor {
            get {
                return ResourceManager.GetString("Abbreviations_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------- ABBREVIATIONS LIST EMPTY --------.
        /// </summary>
        internal static string ABBREVIATIONS_LIST_EMPTY {
            get {
                return ResourceManager.GetString("ABBREVIATIONS_LIST_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Abbreviation.
        /// </summary>
        internal static string Add_Abbreviation {
            get {
                return ResourceManager.GetString("Add_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Abbreviation .
        /// </summary>
        internal static string Add_Abbreviation1 {
            get {
                return ResourceManager.GetString("Add_Abbreviation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; already exists.
        /// </summary>
        internal static string already_exists {
            get {
                return ResourceManager.GetString("already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Save. Abbr for &apos;.
        /// </summary>
        internal static string Can_Save_Abbr_for {
            get {
                return ResourceManager.GetString("Can_Save_Abbr_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and Quit?.
        /// </summary>
        internal static string Cancel_and_Quit {
            get {
                return ResourceManager.GetString("Cancel_and_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter?.
        /// </summary>
        internal static string Clear_filter {
            get {
                return ResourceManager.GetString("Clear_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close and Exit?.
        /// </summary>
        internal static string Close_and_Exit {
            get {
                return ResourceManager.GetString("Close_and_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  . Continue?.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit / Add Abbreviation.
        /// </summary>
        internal static string Edit_Add_Abbreviation {
            get {
                return ResourceManager.GetString("Edit_Add_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit/Delete Abbreviation.
        /// </summary>
        internal static string Edit_Delete_Abbreviation {
            get {
                return ResourceManager.GetString("Edit_Delete_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion.
        /// </summary>
        internal static string Expansion {
            get {
                return ResourceManager.GetString("Expansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion is empty.
        /// </summary>
        internal static string Expansion_is_empty {
            get {
                return ResourceManager.GetString("Expansion_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .	------------- NEXT PAGE  -------------.
        /// </summary>
        internal static string NEXT_PAGE {
            get {
                return ResourceManager.GetString("NEXT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .  -------- NOT FOUND.  ADD THIS ABBREVIATION --------.
        /// </summary>
        internal static string NOT_FOUND_ADD_THIS_ABBREVIATION {
            get {
                return ResourceManager.GetString("NOT_FOUND_ADD_THIS_ABBREVIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page .
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an abbreviation!.
        /// </summary>
        internal static string Please_enter_an_abbreviation {
            get {
                return ResourceManager.GetString("Please_enter_an_abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .	------------- PREVIOUS PAGE  -------------.
        /// </summary>
        internal static string PREVIOUS_PAGE {
            get {
                return ResourceManager.GetString("PREVIOUS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Abbreviation and Quit?.
        /// </summary>
        internal static string Save_Abbreviation_and_Quit {
            get {
                return ResourceManager.GetString("Save_Abbreviation_and_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .	------------- SORT A-Z -------------.
        /// </summary>
        internal static string SORT {
            get {
                return ResourceManager.GetString("SORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .	------------- SORT Z-A -------------.
        /// </summary>
        internal static string SORT1 {
            get {
                return ResourceManager.GetString("SORT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoken.
        /// </summary>
        internal static string Spoken {
            get {
                return ResourceManager.GetString("Spoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string SuspensionPoints {
            get {
                return ResourceManager.GetString("SuspensionPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Change?.
        /// </summary>
        internal static string Undo_Change {
            get {
                return ResourceManager.GetString("Undo_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written.
        /// </summary>
        internal static string Written {
            get {
                return ResourceManager.GetString("Written", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are changing existing abbr .
        /// </summary>
        internal static string You_are_changing_existing_abbr {
            get {
                return ResourceManager.GetString("You_are_changing_existing_abbr", resourceCulture);
            }
        }
    }
}
