<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VersionPrefix>3.13.0</VersionPrefix>
    <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <InformationalVersion>$(VersionPrefix)</InformationalVersion>
    <BaseOutputPath>$(SolutionDir)\artifacts\</BaseOutputPath>
    <IntermediateOutputPath>$(BaseOutputPath)\obj\$(Platform)\$(Configuration)</IntermediateOutputPath>
    <BuildPath>$(BaseOutputPath)\bin\$(Platform)\$(Configuration)\</BuildPath>
    <OutputPath>$(BuildPath)</OutputPath>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
  </PropertyGroup>
</Project>