<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="3.7.0" />
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ACATCore\ACAT.Core.csproj" />
  </ItemGroup>
</Project>
