//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACAT.Extensions.Hawking.FunctionalAgents.SwitchWindows
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwitchWindowsAgent.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Applications.
        /// </summary>
        internal static string Active_Applications {
            get {
                return ResourceManager.GetString("Active_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter?.
        /// </summary>
        internal static string Clear_filter {
            get {
                return ResourceManager.GetString("Clear_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close and exit?.
        /// </summary>
        internal static string Close_and_exit {
            get {
                return ResourceManager.GetString("Close_and_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .	------------- NEXT PAGE  -------------.
        /// </summary>
        internal static string NEXT_PAGE {
            get {
                return ResourceManager.GetString("NEXT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------- NO ACTIVE WINDOWS -------------.
        /// </summary>
        internal static string NO_ACTIVE_WINDOWS {
            get {
                return ResourceManager.GetString("NO_ACTIVE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page .
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .	------------- PREVIOUS PAGE  -------------.
        /// </summary>
        internal static string PREVIOUS_PAGE {
            get {
                return ResourceManager.GetString("PREVIOUS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Desktop.
        /// </summary>
        internal static string Show_Desktop {
            get {
                return ResourceManager.GetString("Show_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .	------------- SORT Z-A -------------.
        /// </summary>
        internal static string SORT {
            get {
                return ResourceManager.GetString("SORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .	------------- SORT A-Z -------------.
        /// </summary>
        internal static string SORT1 {
            get {
                return ResourceManager.GetString("SORT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string SuspensionPoints {
            get {
                return ResourceManager.GetString("SuspensionPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to .
        /// </summary>
        internal static string Switch_to {
            get {
                return ResourceManager.GetString("Switch_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window does not exist.
        /// </summary>
        internal static string Window_does_not_exist {
            get {
                return ResourceManager.GetString("Window_does_not_exist", resourceCulture);
            }
        }
    }
}
