//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACAT.Extensions.Default.WordPredictors.Presage.PresageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Presage/2015/03/10", ConfigurationName="PresageService.Presage")]
    public interface Presage {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/predict", ReplyAction="urn:Presage/2015/03/10/Presage/predictResponse")]
        string[] predict(string previous_words, string current_word);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/predict", ReplyAction="urn:Presage/2015/03/10/Presage/predictResponse")]
        System.Threading.Tasks.Task<string[]> predictAsync(string previous_words, string current_word);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/context", ReplyAction="urn:Presage/2015/03/10/Presage/contextResponse")]
        string context();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/context", ReplyAction="urn:Presage/2015/03/10/Presage/contextResponse")]
        System.Threading.Tasks.Task<string> contextAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/context_change", ReplyAction="urn:Presage/2015/03/10/Presage/context_changeResponse")]
        bool context_change();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/context_change", ReplyAction="urn:Presage/2015/03/10/Presage/context_changeResponse")]
        System.Threading.Tasks.Task<bool> context_changeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/prefix", ReplyAction="urn:Presage/2015/03/10/Presage/prefixResponse")]
        string prefix();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/prefix", ReplyAction="urn:Presage/2015/03/10/Presage/prefixResponse")]
        System.Threading.Tasks.Task<string> prefixAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/learn", ReplyAction="urn:Presage/2015/03/10/Presage/learnResponse")]
        void learn(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/learn", ReplyAction="urn:Presage/2015/03/10/Presage/learnResponse")]
        System.Threading.Tasks.Task learnAsync(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/completion", ReplyAction="urn:Presage/2015/03/10/Presage/completionResponse")]
        string completion(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/completion", ReplyAction="urn:Presage/2015/03/10/Presage/completionResponse")]
        System.Threading.Tasks.Task<string> completionAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/get_config", ReplyAction="urn:Presage/2015/03/10/Presage/get_configResponse")]
        string get_config(string variable);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/get_config", ReplyAction="urn:Presage/2015/03/10/Presage/get_configResponse")]
        System.Threading.Tasks.Task<string> get_configAsync(string variable);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/set_config", ReplyAction="urn:Presage/2015/03/10/Presage/set_configResponse")]
        void set_config(string variable, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/set_config", ReplyAction="urn:Presage/2015/03/10/Presage/set_configResponse")]
        System.Threading.Tasks.Task set_configAsync(string variable, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/save_config", ReplyAction="urn:Presage/2015/03/10/Presage/save_configResponse")]
        void save_config();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Presage/2015/03/10/Presage/save_config", ReplyAction="urn:Presage/2015/03/10/Presage/save_configResponse")]
        System.Threading.Tasks.Task save_configAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PresageChannel : ACAT.Extensions.Default.WordPredictors.Presage.PresageService.Presage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PresageClient : System.ServiceModel.ClientBase<ACAT.Extensions.Default.WordPredictors.Presage.PresageService.Presage>, ACAT.Extensions.Default.WordPredictors.Presage.PresageService.Presage {
        
        public PresageClient() {
        }
        
        public PresageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PresageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PresageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PresageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] predict(string previous_words, string current_word) {
            return base.Channel.predict(previous_words, current_word);
        }
        
        public System.Threading.Tasks.Task<string[]> predictAsync(string previous_words, string current_word) {
            return base.Channel.predictAsync(previous_words, current_word);
        }
        
        public string context() {
            return base.Channel.context();
        }
        
        public System.Threading.Tasks.Task<string> contextAsync() {
            return base.Channel.contextAsync();
        }
        
        public bool context_change() {
            return base.Channel.context_change();
        }
        
        public System.Threading.Tasks.Task<bool> context_changeAsync() {
            return base.Channel.context_changeAsync();
        }
        
        public string prefix() {
            return base.Channel.prefix();
        }
        
        public System.Threading.Tasks.Task<string> prefixAsync() {
            return base.Channel.prefixAsync();
        }
        
        public void learn(string text) {
            base.Channel.learn(text);
        }
        
        public System.Threading.Tasks.Task learnAsync(string text) {
            return base.Channel.learnAsync(text);
        }
        
        public string completion(string token) {
            return base.Channel.completion(token);
        }
        
        public System.Threading.Tasks.Task<string> completionAsync(string token) {
            return base.Channel.completionAsync(token);
        }
        
        public string get_config(string variable) {
            return base.Channel.get_config(variable);
        }
        
        public System.Threading.Tasks.Task<string> get_configAsync(string variable) {
            return base.Channel.get_configAsync(variable);
        }
        
        public void set_config(string variable, string value) {
            base.Channel.set_config(variable, value);
        }
        
        public System.Threading.Tasks.Task set_configAsync(string variable, string value) {
            return base.Channel.set_configAsync(variable, value);
        }
        
        public void save_config() {
            base.Channel.save_config();
        }
        
        public System.Threading.Tasks.Task save_configAsync() {
            return base.Channel.save_configAsync();
        }
    }
}
