name: Build ACAT

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release, Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true   # Enable Git LFS

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore NuGet packages before building
    - name: Restore dependencies
      run: dotnet restore ACAT.sln
      working-directory: src/
          
    # Build the full application
    - name: Build the Solution
      run: |
        msbuild acat.sln /t:Build /p:Configuration=${{ matrix.configuration }}
      working-directory: src/
    
    # Execute all tests (Debug configuration only)
    - name: Run ACATCore.Tests.Logging
      if: matrix.configuration == 'Debug'
      run: >
        dotnet test Libraries/ACATCore.Tests.Logging/ACATCore.Tests.Logging.csproj
        --configuration Debug
        --logger "console;verbosity=normal"
      working-directory: src/
      continue-on-error: false

    - name: Run ACATCore.Tests.Configuration
      if: matrix.configuration == 'Debug'
      run: >
        dotnet test Libraries/ACATCore.Tests.Configuration/ACATCore.Tests.Configuration.csproj
        --configuration Debug
        --no-build
        --logger "console;verbosity=normal"
      working-directory: src/
      continue-on-error: false

    - name: Run ACATCore.Tests.Integration
      if: matrix.configuration == 'Debug'
      run: >
        dotnet test Libraries/ACATCore.Tests.Integration/ACATCore.Tests.Integration.csproj
        --configuration Debug
        --logger "console;verbosity=normal"
      working-directory: src/
      continue-on-error: false

    - name: Run ACAT.ConfigMigrationTool.Tests
      if: matrix.configuration == 'Debug'
      run: >
        dotnet test Applications/ConfigMigrationTool/ACAT.ConfigMigrationTool.Tests/ACAT.ConfigMigrationTool.Tests.csproj
        --configuration Debug
        --logger "console;verbosity=normal"
      working-directory: src/
      continue-on-error: false
      
    - name: Upload release build artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: acat_${{ matrix.configuration }}
        path: src/Applications/ACATApp/bin/${{ matrix.configuration }}

