<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="3.0.0" />
    <ProjectReference Include="..\..\..\..\ACATResources\ACATResources.csproj" />
    <ProjectReference Include="$(SolutionRoot)Libraries\ACATCore\ACAT.Core.csproj" />
    <ProjectReference Include="$(SolutionRoot)Libraries\ACATExtension\ACAT.Extension.csproj" />
    <ProjectReference Include="..\EEGSettings\ACAT.Extensions.BCI.Actuators.EEG.EEGSettings.csproj" />
    <ProjectReference Include="..\..\Common\AnimationSharp\ACAT.Extensions.BCI.Common.AnimationSharp.csproj" />
    <ProjectReference Include="..\..\Common\BCIControl\ACAT.Extensions.BCI.Common.BCIControl.csproj" />
    <ProjectReference Include="..\..\Common\BCIInterfaceUtilities\ACAT.Extensions.BCI.Common.BCIInterfaceUtilities.csproj" />
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Numerics" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Windows.Forms.DataVisualization" />
    <PackageReference Include="Accord" Version="3.8.0.0" />
    <PackageReference Include="Accord.Math" Version="3.8.0.0" />
    <PackageReference Include="Accord.Statistics" Version="3.8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="System.Resources.Extensions" Version="10.0.3" />
  </ItemGroup>
</Project>